constexpr char BACKGROUND_VERT_GLSL[] = 
"#version 440 core\n"
"layout (location = 0) in vec2 vertex_position;\n"
"layout (location = 1) in vec2 texture_position;\n"
"layout (location = 2) in vec3 colour;\n"
"layout (std140, binding = 0) uniform CommonData {\n"
"  mat4 projection_;\n"
"  vec2 set_position_;\n"
"};\n"
"out FS_DATA\n"
"{\n"
"  vec2 texture_position;\n"
"  vec3 colour;\n"
"} fs_data;\n"
"void main()\n"
"{\n"
"  gl_Position = projection_ * vec4(vertex_position, 0.0f, 1.0f);\n"
"  fs_data.texture_position = texture_position;\n"
"  fs_data.colour = colour;\n"
"}";

constexpr char BACKGROUND_FRAG_GLSL[] = 
"#version 440 core\n"
"out vec4 fragment_colour;\n"
"uniform sampler2D bg_texture;\n"
"in FS_DATA\n"
"{\n"
"  vec2 texture_position;\n"
"  vec3 colour;\n"
"} fs_data;\n"
"void main()\n"
"{\n"
"  fragment_colour = texture(bg_texture, fs_data.texture_position) * vec4(fs_data.colour, 1.0);\n"
"}";
