constexpr char CHARACTER_VERT_GLSL[] = 
"#version 440 core\n"
"layout (location = 0) in vec2 position;\n"
"layout (location = 1) in float has_texture;\n"
"layout (location = 2) in vec2 texture_position;\n"
"layout (location = 3) in vec4 colour;\n"
"layout (std140, binding = 0) uniform CommonData {\n"
"	mat4 projection_;\n"
"	vec2 set_position_;\n"
"};\n"
"out FS_DATA\n"
"{\n"
"	vec2 texture_position;\n"
"	float has_texture;\n"
"	vec4 colour;\n"
"} fs_data;\n"
"void main()\n"
"{\n"
"	gl_Position = projection_ * vec4(set_position_ + position, 0.0f, 1.0f);\n"
"	fs_data.texture_position = texture_position;\n"
"	fs_data.has_texture = has_texture;\n"
"	fs_data.colour = colour;\n"
"}";

constexpr char CHARACTER_FRAG_GLSL[] = 
"#version 440 core\n"
"out vec4 fragment_colour;\n"
"uniform usampler2D font_texture;\n"
"in FS_DATA\n"
"{\n"
"	vec2 texture_position;\n"
"	float has_texture;\n"
"	vec4 colour;\n"
"} fs_data;\n"
"void main()\n"
"{\n"
"	fragment_colour = fs_data.colour;\n"
"	if (fs_data.has_texture > 0.0) {\n"
"		float sampled = texture(font_texture, fs_data.texture_position).r;\n"
"		fragment_colour.w *= sampled;\n"
"	}\n"
"}";
