constexpr char DEFAULT_VERT_GLSL[] = 
"#version 440 core\n"
"layout (location = 0) in vec2 vertex_position;\n"
"layout (location = 1) in vec2 texture_position;\n"
"layout (location = 2) in vec4 colour;\n"
"layout (std140, binding = 0) uniform CommonData {\n"
"	mat4 projection_;\n"
"};\n"
"out FS_DATA\n"
"{\n"
"	vec2 texture_position;\n"
"	vec4 colour;\n"
"} fs_data;\n"
"void main()\n"
"{\n"
"	gl_Position = projection_ * vec4(vertex_position, 0.0f, 1.0f);\n"
"	fs_data.texture_position = texture_position;\n"
"	fs_data.colour = colour;\n"
"}";

constexpr char DEFAULT_FRAG_GLSL[] = 
"#version 440 core\n"
"out vec4 fragment_colour;\n"
"uniform sampler2D fragment_texture;\n"
"in FS_DATA\n"
"{\n"
"	vec2 texture_position;\n"
"	vec4 colour;\n"
"} fs_data;\n"
"void main()\n"
"{\n"
" fragment_colour = fs_data.colour;\n"
"	if (fragment_texture > 0) {\n"
"		fragment_colour = texture(fragment_texture, fs_data.texture_position);\n"
"	}\n"
"}";
